services:
  # DEVICE
  device-verifier:
    # Runs on port 8090
    image: dockerhub.odins.es/unimaas/oidc4vp:latest
    container_name: device-verifier
    networks:
      - device
    command: ["verifier"]
    environment:
      logs: "false"
      xacml: "true"
      xacml_domain: unimaas
      xacml_pdp: https://unimaas.odins.es/pdp/verdict
      blockchain_rest: https://unimaas.odins.es
      default_vc_template: "UnimaasId"
    restart: unless-stopped

  device-internal:
    # Runs on ports 8081 and 9091
    image: dockerhub.odins.es/unimaas/vo-wot:0.18.15
    container_name: device
    networks:
      - device
    environment:
      HOSTNAME: device
    volumes:
      - ./device/app.py:/app.py
      - ./device/config.yaml:/config.yaml
      - ./device/td.json:/td.json
    restart: unless-stopped

  device-proxy:
    image: dockerhub.odins.es/unimaas/pep-proxy:latest
    container_name: device-proxy
    networks:
      device:
      edge:
        aliases:
          - device
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      # BASIC SETTINGS
      pep_protocol: "http"
      PEP_ENDPOINT: "http://device:8080,http://device:9090"
      oidc4vp_verifier_host: "device-verifier"
      oidc4vp_verifier_port: "8090"
      target_host: "device"
      target_port: "8081"
      target2_host: "device"
      target2_port: "9091"
      target2_thingdescription: "/device"
    depends_on:
      - device-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  device-holder:
    # Runs on port 8085
    image: dockerhub.odins.es/unimaas/oidc4vp:latest
    container_name: device-holder
    networks:
      - device
    command: ["holder"]
    environment:
      logs: "false"
      blockchain_rest: https://unimaas.odins.es
      issuer_host: https://unimaas.odins.es/issuer
    restart: unless-stopped

  # VO
  vo-internal:
    # Runs on ports 8080 and 9090
    image: dockerhub.odins.es/unimaas/vo-wot:0.18.15
    container_name: vo
    networks:
      - vo
      - edge
    environment:
      HOSTNAME: localhost
    volumes:
      - ./vo/app.py:/app.py
      - ./vo/config.yaml:/config.yaml
      - ./vo/td.json:/td.json
    restart: unless-stopped

  vo-holder:
    # Runs on port 8085
    image: dockerhub.odins.es/unimaas/oidc4vp:latest
      # image: tfm/oidc-security:latest
    container_name: vo-holder
    networks:
      - vo
      - edge
    command: ["holder"]
    environment:
      logs: "false"
      blockchain_rest: https://unimaas.odins.es
      issuer_host: https://unimaas.odins.es/issuer
    depends_on:
      - device-internal
      - device-proxy
    restart: unless-stopped

networks:
  device:
  edge:
  vo:
