name: vo
type: VO
resourceType:
  specification: WoT
  version: 1.1
deploymentType: A
catalogue: 9090
bindingNB:
  bindingModeNB: [H]
  hostname: localhost
  ports:
    httpPort: 8080
bindingSB:
  bindingModeSB: [H]
  securitySB:
    securitySBHTTP:
      securityScheme: oidc4vp
      holderUrl: "http://vo-holder:8085"
      requester: vo
databaseConfig:
  timeseriesDB:
    influxDB: disabled
  persistentDB:
    SQLite: enabled
consumedVOs:
  vo1:
    url: "http://device:9090/device"
proxy:
  propertiesMap:
    temperature: vo1
