
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

###############################################################################
# INPUT PLUGINS
###############################################################################

[[inputs.http]]
  urls = ["http://aas-env:8081/submodels/dXJuOmFhczpzdWJtb2RlbDpwcm9jZXNzOnRlc3Q=/submodel-elements"]
  data_format = "json"
  json_query = "result"
  tag_keys = []
  json_name_key = "idShort"
  name_override = "DeviceAAS"
  [inputs.http.tags]
    device = "1234"

# Temperature topic
# [[inputs.mqtt_consumer]]
#   servers = ["tcp://mosquitto:1883"]
#   topics = ["device/1234/temperature"]
#   qos = 0
#   connection_timeout = "30s"
#   username = ""
#   password = ""
#   data_format = "value"
#   data_type = "float"
#   name_override = "temperature"
#   # Add a static tag for device (not extracted automatically)
#   [inputs.mqtt_consumer.tags]
#     device = "1234"

# # Humidity topic
# [[inputs.mqtt_consumer]]
#   servers = ["tcp://mosquitto:1883"]
#   topics = ["device/1234/humidity"]
#   qos = 0
#   connection_timeout = "30s"
#   username = ""
#   password = ""
#   data_format = "value"
#   data_type = "float"
#   name_override = "humidity"
#   [inputs.mqtt_consumer.tags]
#     device = "1234"

###############################################################################
# OUTPUT PLUGINS
###############################################################################

[[outputs.influxdb_v2]]
  ## URLs of the InfluxDB cluster
  urls = ["http://influxdb:8086"]
  ## Token for authentication
  token = "S18VeAlq042B4naMX31oqIaSGmUmOLAC-DV3VIdkxDJuAhTXLTVFEchyTSmCcUAmB7Wu94KgExzV8gJaDjzR3Q=="
  organization = "wot"
  bucket = "my-bucket"