name: device
type: VO
resourceType:
  specification: WoT
  version: 1.1
deploymentType: A
catalogue: 9097
bindingNB:
  bindingModeNB: [H]
  hostname: device-bcontainer
  ports:
    httpPort: 8085
databaseConfig:
  timeseriesDB:
    influxDB: disabled
  persistentDB:
    SQLite: disabled
# periodicFunction:
#   damage_simulation: 200000
