name: Container
type: VO
resourceType:
  specification: WoT
  version: 1.1
deploymentType: A
catalogue: 9090
bindingNB:
  # bindingModeNB: [H, M, U, WS]
  bindingModeNB: [H]
  hostname: localhost
  ports:
    httpPort: 8080
bindingSB:
  bindingModeSB: [H]
databaseConfig:
  timeseriesDB:
    influxDB: disabled
  persistentDB:
    SQLite: disabled
consumedVOs:
  device:
    url: "http://localhost:9091/device" # assume the device VO is running on port 9091
    events:
      - damageDetected